=== DAW-EDIX-Grupo-molon/ActividadesLenguajesDeMarca/AE-2/Ivan/biblioteca.dtd
<!ELEMENT biblioteca (libros?,revistas?,periodicos?)>

<!-- Libros -->
<!ELEMENT libros (libro+)>

<!ELEMENT libro (titulo,capitulo+,indice?,sinopsis*)>
<!ATTLIST libro id ID #REQUIRED>
<!ATTLIST libro num_paginas CDATA #REQUIRED>
<!ATTLIST libro tipo_clase (novela|infantil|didactico) #REQUIRED>

<!ELEMENT titulo (#PCDATA)>

<!ELEMENT capitulo (contenido)>
<!ATTLIST capitulo paginas CDATA #REQUIRED>

<!ELEMENT contenido (#PCDATA)>
<!ATTLIST contenido enlace CDATA #REQUIRED>

<!ELEMENT indice (capitulos*)>

<!ELEMENT capitulos (nom_cap,paginas)>

<!ELEMENT nom_cap (#PCDATA)>

<!ELEMENT paginas (#PCDATA)>

<!ELEMENT sinopsis (#PCDATA)>

<!-- Revistas -->
<!ELEMENT revistas (revista+)>

<!ELEMENT revista (titulo,numero,indice?,seccion+)>
<!ATTLIST revista id ID #REQUIRED>
<!ATTLIST revista tipo_clase (informatica|corazon|coches|investigacion|otras) #REQUIRED>
<!ATTLIST revista paginas CDATA #REQUIRED>

<!ELEMENT numero (#PCDATA)>

<!ELEMENT seccion (contenido)>
<!ATTLIST seccion paginas CDATA #REQUIRED>

<!-- Periodicos -->
<!ELEMENT periodicos (periodico+)>

<!ELEMENT periodico (seccion_p,indice?)>
<!ATTLIST periodico id ID #REQUIRED>
<!ATTLIST periodico tipo_clase (nacionales|internacionales) #REQUIRED>
<!ATTLIST periodico fecha_publicacion CDATA #REQUIRED>

<!ELEMENT seccion_p (articulos)>
<!ATTLIST seccion_p tipo_seccion (económica|opinión|deportes|nacional|internacional) #REQUIRED>

<!ELEMENT articulos (contenido)>
<!ATTLIST articulos autor CDATA #REQUIRED>

=== DAW-EDIX-Grupo-molon/ActividadesLenguajesDeMarca/AE-2/Ivan/biblioteca-dtd.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE biblioteca SYSTEM "biblioteca.dtd">
<biblioteca>
    <libros>
        <libro id="l1111" num_paginas="672" tipo_clase="novela">
            <titulo>El Imperio Final</titulo>
            <capitulo paginas="15">
                <contenido enlace="enlace_cap1">Cap1</contenido>
            </capitulo>
            <capitulo paginas="18">
                <contenido enlace="enlace_cap2">Cap2</contenido>
            </capitulo>
            <capitulo paginas="12">
                <contenido enlace="enlace_cap3">Cap3</contenido>
            </capitulo>
            <indice>
                <capitulos>
                    <nom_cap>1</nom_cap>
                    <paginas>20</paginas>
                </capitulos>
            </indice>

            <sinopsis>Durante mil años han caído las cenizas y nada florece. Durante mil años los skaa han sido esclavizados y viven sumidos en un miedo inevitable. Durante mil años el Lord Legislador reina con un poder absoluto gracias al terror, a sus poderes e inmortalidad. Le ayudan «obligadores» e «inquisidores», junto a la poderosa magia de la «alomancia». Pero los nobles a menudo han tenido trato sexual con jóvenes skaa y, aunque la ley lo prohíbe, algunos de sus bastardos han sobrevivido y heredado los poderes alománticos: son los «nacidos de la bruma» (mistborns). Ahora, Kelsier, el «superviviente», el único que ha logrado huir de los Pozos de Hathsin, ha encontrado a Vin, una pobre chica skaa con mucha suerte... Tal vez los dos, unidos a la rebelión que los skaa intentan desde hace mil años, logren cambiar el mundo y la atroz dominación del Lord Legislador.</sinopsis>
        </libro>
    </libros>
    <revistas>
        <revista id="r1111" tipo_clase="informática" paginas="50">
            <titulo>Rolling Stone</titulo>
            <numero>187</numero>
            <indice/>
            <seccion paginas="3">
                <contenido enlace="enlace_sec1">sec1</contenido>
            </seccion>
            <seccion paginas="2">
                <contenido enlace="enlace_sec1">sec2</contenido>
            </seccion>
            <seccion paginas="6">
                <contenido enlace="enlace_sec1">sec3</contenido>
            </seccion>
        </revista>
    </revistas>
    <periodicos>
        <periodico id="p1111" tipo_clase="internacionales" fecha_publicacion="07/05/2023">
            <seccion_p tipo_seccion="opinión">
                <articulos autor="EMILIA LANDALUCE">
                    <contenido enlace="enlace_art1">art1</contenido>
                </articulos>
            </seccion_p>
            <indice></indice>
        </periodico>
    </periodicos>
</biblioteca>
