=== DAW-EDIX-Grupo-molon/ActividadesLenguajesDeMarca/AE-2/Laura/dtd.dtd
<!ELEMENT biblioteca (libros, periodicos, revistas)>

<!-- Libros -->
<!ELEMENT libros (libro+)>
<!ELEMENT libro (titulo, capitulo+, indice, sinopsis)>
<!ATTLIST libro id ID #REQUIRED tipo_clase CDATA #REQUIRED>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT capitulo (contenido)>
<!ATTLIST capitulo titulo CDATA #REQUIRED num_paginas CDATA #REQUIRED>
<!ELEMENT contenido EMPTY>
<!ATTLIST contenido enlace CDATA #REQUIRED>
<!ELEMENT indice  EMPTY>
<!ATTLIST indice num_paginas CDATA #REQUIRED>
<!ELEMENT sinopsis (#PCDATA)>

<!-- Periodicos -->
<!ELEMENT periodicos (periodico+)>
<!ELEMENT periodico (seccionpe+, indicep)>
<!ATTLIST periodico id ID #REQUIRED>
<!ATTLIST periodico tipo_clase CDATA #REQUIRED>
<!ATTLIST periodico fecha_publicacion CDATA #REQUIRED>
<!ELEMENT seccionpe (articulo, contenidop)>
<!ATTLIST seccionpe tipo CDATA #REQUIRED>
<!ELEMENT articulo (#PCDATA)>
<!ATTLIST articulo autor CDATA #REQUIRED>
<!ELEMENT contenidop EMPTY>
<!ATTLIST contenidop enlace CDATA #REQUIRED>
<!ELEMENT indicep  EMPTY>
<!ATTLIST indicep num_paginas CDATA #REQUIRED>

<!-- Revistas -->
<!ELEMENT revistas (revista+)>
<!ELEMENT revista (titulo, indice, secciones)>
<!ATTLIST revista
          id CDATA #REQUIRED
          tipo_re CDATA #REQUIRED
          num_revista CDATA #REQUIRED>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT indice (#PCDATA)>
<!ELEMENT secciones (seccion+)>
<!ELEMENT seccion (contenidor)>
<!ATTLIST seccion
          tipo CDATA #REQUIRED
          num_paginas CDATA #REQUIRED>
<!ELEMENT contenidor (#PCDATA | enlace)*>
<!ATTLIST contenidor enlace CDATA #REQUIRED>

=== DAW-EDIX-Grupo-molon/ActividadesLenguajesDeMarca/AE-2/Laura/bliblioteca_dtd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE biblioteca SYSTEM "dtd.dtd">
<biblioteca>
    <libros>
        <libro id="L0001" tipo_clase= "novela">
            <titulo>Lo que el viento se llevó</titulo>
            <capitulo titulo="Capítulo 1" num_paginas="60">
                <contenido enlace="http://loqueelvientosellevo.com/capitulo1"/>
            </capitulo>
            <capitulo titulo="Capítulo 2" num_paginas="55">
                <contenido enlace="http://loquevientosellevo.com/capitulo2"/>
            </capitulo>
            <indice num_paginas="2"/>
            <sinopsis>Pues lo que el viento se llevó y no volvió</sinopsis>
        </libro>

        <libro id="L0002" tipo_clase="infantil">
            <titulo>El capitán calzoncillos</titulo>
            <capitulo titulo="Capítulo 1" num_paginas="15">
                <contenido enlace="http://barcodevapor.com/capitulo1"/>
            </capitulo>
            <capitulo titulo="Capítulo 2" num_paginas="12">
                <contenido enlace="http://barcodevapor.com/capitulo2"/>
            </capitulo>
            <indice num_paginas="1"/>
            <sinopsis>Un joven que va en calzonillos</sinopsis>
        </libro>

        <libro id="L0003" tipo_clase="didactico">
            <titulo>MacMillan Tiger 5 student book</titulo>
            <capitulo titulo="Sport" num_paginas="15">
                <contenido enlace="http://tiger.macmillan.es//page5"/>
            </capitulo>
            <capitulo titulo="The weather" num_paginas="12">
                <contenido enlace="http://tiger.macmillan.es//page40"/>
            </capitulo>
            <indice num_paginas="4"/>
            <sinopsis>Libro educativo de inglés</sinopsis>
        </libro>
    </libros>

    <periodicos>

        <periodico id="P1234" tipo_clase="nacional" fecha_publicacion="2023-04-08">
                <seccionpe tipo="cronica">
                    <articulo autor="Sergio Lorenzo">El terrible caso del 'sádico de Cáceres'</articulo>
                    <contenidop enlace="https://www.hoy.es/extremadura/cronica-negra/terrible-sadico-caceres-20230406080842-nt.html"/>
                </seccionpe>
                <seccionpe tipo="sucesos">
                    <articulo autor="R. H.">Roban 9.500 euros a un vecino de Montijo con la estafa 'call spoofing'</articulo>
                    <contenidop enlace="https://www.hoy.es/prov-badajoz/roban-9500-euros-vecino-montijo-estafa-call-20230504130133-nt.html"/>
                </seccionpe>
                <indicep num_paginas="1"/>
            </periodico>

            <periodico id="P2222" tipo_clase="internacional" fecha_publicacion="2023-05-04">
                <seccionpe tipo="opinion">
                    <articulo autor="Damon Winter">In Mississippi, the Governor Has Been So Bad That This Time It Might Be Different</articulo>
                    <contenidop enlace="https://www.nytimes.com/international/section/opinion"/>
                </seccionpe>
                <seccionpe tipo="deportes">
                    <articulo autor="Victor Mather">Knicks vs. Heat: Brawls, Nail-Biters and a Clinging Coach</articulo>
                    <contenidop enlace="https://www.nytimes.com/2023/04/27/sports/basketball/knicks-heat-nba-playoffs.html"/>
                </seccionpe>
                <indicep num_paginas="1"/>
            </periodico>
    
    </periodicos>

    <revistas>
        <revista id="R1" tipo_re="informática" num_revista="11">
            <titulo>Revista de informática</titulo>
            <indice num_paginas="1"/>
            <secciones>
                <seccion tipo="noticias" num_paginas="10">
                <contenidor enlace="https://siliconnews.plataformasinc.es/hardware/"/>
                </seccion>
                <seccion tipo="artículos" num_paginas="11">
                <contenidor enlace="https://siliconnews.plataformasinc.es/internet/"/>
                </seccion>
            </secciones>
        </revista>

        <revista id="R2" tipo_re="coches" num_revista="05">
            <titulo>Revista de informática</titulo>
            <indice num_paginas="2"/>
            <secciones>
                <seccion tipo="noticias" num_paginas="5">
                <contenidor enlace="https://revistacar.es/car-store-vehiculos/"/>
                </seccion>
                <seccion tipo="de interés" num_paginas="1">
                <contenidor enlace="https://siliconnews.plataformasinc.es/magzine-pruebs/"/>
                </seccion>
            </secciones>
        </revista>
    
        <revista id="R3" tipo_re="coraazón" num_revista="350">
            <titulo>Revista de informática</titulo>
            <indice num_paginas="2"/>
            <secciones>
                <seccion tipo="moda" num_paginas="16">
                <contenidor enlace="https://hola.com/moda/tendencias/"/>
                </seccion>
                <seccion tipo="horoscopo" num_paginas="6">
                <contenidor enlace="https://hola.com/horoscopo/"/>
                </seccion>
            </secciones>
        </revista>
    </revistas>
</biblioteca>
